name: Dev feature disabled compatibility integration test
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      INTEGRATION_TEST: true
      DEV_FEATURES_ENABLED: false
    steps:
      - uses: logto-io/actions-package-logto-artifact@v2
        with:
          artifact-name: dev-feature-disabled-integration-test-${{ github.sha }}
          pnpm-version: 9

  run-logto:
    strategy:
      fail-fast: false
      matrix:
        target: [api, experience, console]
    runs-on: ubuntu-latest
    env:
      INTEGRATION_TEST: true
      DEV_FEATURES_ENABLED: false
      DB_URL: postgres://postgres:postgres@localhost:5432/postgres
    steps:
      - uses: logto-io/actions-run-logto-integration-tests@v3
        with:
          logto-artifact: dev-feature-disabled-integration-test-${{ github.sha }}
          test-target: ${{ matrix.target }}
          pnpm-version: 9
