name: Integration Test

on:
  push:
    branches:
      - master
      - "push-action/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: buildjet-4vcpu-ubuntu-2204
    env:
      INTEGRATION_TEST: true

    steps:
      - uses: logto-io/actions-package-logto-artifact@v2
        with:
          artifact-name: integration-test-${{ github.sha }}
          pnpm-version: 9

  run-logto:
    strategy:
      fail-fast: false
      matrix:
        target: [api, experience, console]
    needs: package
    runs-on: ubuntu-latest
    env:
      INTEGRATION_TEST: true
      DB_URL: postgres://postgres:postgres@localhost:5432/postgres

    steps:
      - uses: logto-io/actions-run-logto-integration-tests@v3
        with:
          logto-artifact: integration-test-${{ github.sha }}
          test-target: ${{ matrix.target }}
          pnpm-version: 9
