name: Integration Test

on:
  push:
    branches:
      - master
      - "push-action/**"
  pull_request:

concurrency:
  group: integration-test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2

      - name: Build
        run: pnpm -- lerna run build --stream

      - name: Package
        run: ./package.sh

      - uses: actions/upload-artifact@v3
        with:
          name: integration-test-${{ github.sha }}
          path: /tmp/logto.tar.gz
          retention-days: 3

  run-logto:
    needs: package

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          path: tests

      - name: Copy lockfile
        run: |
          cp tests/pnpm-lock.yaml ./
          cp tests/package.json ./

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2
        with:
          run-install: false

      # Setup integration test
      - name: Install dependencies
        run: |
          cd tests
          pnpm i
          pnpm prepack

      # Setup environment
      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v3

      - uses: actions/download-artifact@v3
        with:
          name: integration-test-${{ github.sha }}

      - name: Extract
        working-directory: tests
        run: |
          npm run cli init -- -p ../logto --db postgres://postgres:postgres@localhost:5432 --no-oc --du ../logto.tar.gz
      
      - name: Add mock connectors
        working-directory: tests
        run: |
          npm run cli connector add @logto/connector-mock-sms @logto/connector-mock-email @logto/connector-mock-social -- -p ../logto

      - name: Run Logto
        working-directory: logto/packages/core
        run: node . &
        env:
          INTEGRATION_TEST: true
          NODE_ENV: production
          DB_URL: postgres://postgres:postgres@localhost:5432

      - name: Sleep for 5 seconds
        run: sleep 5

      # Test
      - name: Run tests
        run: |
          cd tests/packages/integration-tests
          pnpm start
        env:
          INTEGRATION_TESTS_LOGTO_URL: http://localhost:3001
