name: Master Codecov Report

on:
  push:
    branches: [master]

concurrency: ${{ github.workflow }}

jobs:
  report-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v5
        with:
          pnpm-version: 10
          node-version: ^22.14.0

      - name: Install playwright for element tests
        working-directory: ./packages/elements
        run: pnpm exec playwright install --with-deps

      - name: Build for test
        run: pnpm -r build:test

      - name: Test
        run: pnpm ci:test

      - name: Codecov Core
        uses: codecov/codecov-action@v5
        with:
          flags: core
          directory: ./packages/core
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Codecov UI
        uses: codecov/codecov-action@v5
        with:
          flags: experience
          directory: ./packages/experience
          token: ${{ secrets.CODECOV_TOKEN }}
