name: Publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: Semver bump type
        required: true
      preid:
        description: Pre ID
        required: true
        default: alpha

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_PAT }}

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v1.2.2

      - name: Configure Git user
        run: |
          git config --global user.email bot@silverhand.io
          git config --global user.name silverhand-bot

      - name: Publish to GitHub
        # add `no-verify-access` due to https://github.com/lerna/lerna/issues/2788
        run: |
          pnpm -- lerna publish -m "release: %s" --conventional-commits --preid=${{ github.event.inputs.preid }} --no-verify-access --create-release=github --yes ${{ github.event.inputs.semver }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}

      - name: Package
        run: ./package.sh

      - name: Upload tar to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/logto.tar.gz
