name: Update Metadata

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: logto-io/actions-add-labels-run-steps@v1.1.2
        with:
          title: ${{ github.event.pull_request.title || github.event.issue.title }}
          github-token: ${{ github.token }}

      - name: Add assignees
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ github.token }}
          assignees: ${{ github.actor }}
